!#/bin/bash

echo "CIRCLE_PULL_REQUEST: " $CIRCLE_PULL_REQUEST

echo "CIRCLE_PULL_REQUESTS: "  $CIRCLE_PULL_REQUESTS

echo "CIRCLE_PR_NUMBER: " $CIRCLE_PR_NUMBER

GIT_BRANCH=$(git branch | grep \* | cut -d ' ' -f2)

CIRCLE_USERNAME=$CIRCLE_USERNAMEg
