version: 2
jobs:
  build_git_101:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/exercise
    steps:
      - checkout
      - run:
          name: Printenv
          command: printenv
      - run:
          name: Slack notify
          command: python ./scipt/slack.py

      - run:
          name: Clean remote branche
          command: ./script/clean_git_101.sh

  build_git_102:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/exercise
    steps:
      - checkout
      - run:
          name: Test step
          command: printenv
      - run:
          name: Print env
          command: ./print_env.sh
     
     
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build_git_101:
        filters:
          branches:
            only:
            - feature/git101
    - build_git_102:
        filters:
          branches:
            only:
            - feature/git102/*
    - build_git_101:
        filters:
          branches:
            only:
            - develop

