version: 2
jobs:
  # build job omitted for brevity
  build:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/exercise
    steps:
      - checkout
      - run:
          name: Test step
          command: printenv
      - run:
          name: Print env
          command: ./print_env.sh
#       - run:
#           name: Deploy to S3
#           command: aws s3 sync sang s3://test-circleci29/$CIRCLE_BRANCH/$CIRCLE_SHA1/docs/ --delete
     
     
workflows:
  version: 2
  build-and-deploy:
    jobs:
    - build:
        filters:
          branches:
            only:
            - master
            - develop
            - /feature.*/

