version: 2
jobs:
  build_git_101:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/exercise
    steps:
      - checkout
      - run:
          name: Printenv
          command: printenv; echo 'starting branch' $CIRCLE_BRANCH
      - run:
          name: Upgrading pip
          command: sudo pip install --upgrade pip
      - run:
          name: Install slackclient
          command: sudo pip install slackclient
      - run:
          name: Validate git101
          command: ./scripts/validate_git_101.sh

  build_git_102:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/exercise
    steps:
      - checkout
      - run:
          name: Test step
          command: printenv && echo '102 branch'


  build_dev:
    docker:
      - image: circleci/python:2.7-jessie
    working_directory: ~/exercise
    steps:
      - checkout
      - run:
          name: Printenv
          command: printenv
      - run:
          name: Upgrading pip
          command: sudo pip install --upgrade pip
      - run:
          name: Install slackclient
          command: sudo pip install slackclient

     
workflows:
  version: 2
  validate-git-exercises:
    jobs:
    - build_git_101:
        filters:
          branches:
            only:
            - feature/git101

    - build_git_102:
        filters:
          branches:
            only:
            - /feature/git102/.*/
            
    - build_dev:
        filters:
          branches:
            only:
            - develop

